name: deep_sage
description: "DeepSage – An AI-powered data analysis and visualization tool for uncovering deep insights."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  blur: ^4.0.0
  provider: ^6.1.2
  progressive_button_flutter: ^1.2.0
  font_awesome_flutter: ^10.8.0
  flutter_dotenv: ^5.2.1
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/icons/light/chart.png
    - assets/icons/light/chart_outlined.png
    - assets/icons/light/folder.png
    - assets/icons/light/folder_outlined.png
    - assets/icons/light/home.png
    - assets/icons/light/home_outlined.png
    - assets/icons/light/report.png
    - assets/icons/light/report_outlined.png
    - assets/icons/light/search.png
    - assets/icons/light/search_outlined.png
    - assets/icons/light/settings.png
    - assets/icons/light/settings_outlined.png
    - assets/icons/light/plus.png
    - assets/icons/light/add.png
    - assets/icons/light/ai.png
    - assets/icons/light/factory.png
    - assets/icons/light/government.png


    - assets/icons/dark/chart.png
    - assets/icons/dark/chart_outlined.png
    - assets/icons/dark/folder.png
    - assets/icons/dark/folder_outlined.png
    - assets/icons/dark/home.png
    - assets/icons/dark/home_outlined.png
    - assets/icons/dark/report.png
    - assets/icons/dark/report_outlined.png
    - assets/icons/dark/search.png
    - assets/icons/dark/search_outlined.png
    - assets/icons/dark/settings.png
    - assets/icons/dark/settings_outlined.png
    - assets/icons/dark/plus.png
    - assets/icons/dark/add.png
    - assets/icons/dark/ai.png
    - assets/icons/dark/factory.png
    - assets/icons/dark/government.png
    - assets/larry/larry.png
    - .env
  fonts:
    - family: AfacadFlux
      fonts:
        - asset: assets/fonts/afacad_flux/AfacadFlux-Thin.ttf
          weight: 100
        - asset: assets/fonts/afacad_flux/AfacadFlux-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/afacad_flux/AfacadFlux-Light.ttf
          weight: 300
        - asset: assets/fonts/afacad_flux/AfacadFlux-Regular.ttf
          weight: 400
        - asset: assets/fonts/afacad_flux/AfacadFlux-Medium.ttf
          weight: 500
        - asset: assets/fonts/afacad_flux/AfacadFlux-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/afacad_flux/AfacadFlux-Bold.ttf
          weight: 700
        - asset: assets/fonts/afacad_flux/AfacadFlux-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/afacad_flux/AfacadFlux-Black.ttf
          weight: 900

  uses-material-design: true