name: deep_sage
description: "DeepSage – An AI-powered data analysis and visualization tool for uncovering deep insights."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  fonts:
    - family: AfacadFlux
      fonts:
        - asset: assets/fonts/afacad_flux/AfacadFlux-Thin.ttf
          weight: 100
        - asset: assets/fonts/afacad_flux/AfacadFlux-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/afacad_flux/AfacadFlux-Light.ttf
          weight: 300
        - asset: assets/fonts/afacad_flux/AfacadFlux-Regular.ttf
          weight: 400
        - asset: assets/fonts/afacad_flux/AfacadFlux-Medium.ttf
          weight: 500
        - asset: assets/fonts/afacad_flux/AfacadFlux-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/afacad_flux/AfacadFlux-Bold.ttf
          weight: 700
        - asset: assets/fonts/afacad_flux/AfacadFlux-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/afacad_flux/AfacadFlux-Black.ttf
          weight: 900

  uses-material-design: true