name: Flutter Build (Windows / Linux)

on:
  push:
    branches: [dev]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Get packages
        run: flutter pub get

      - name: Build Linux
        run: flutter build linux

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: linux-build
          path: build/linux/x64/release/bundle/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          channel: stable

      - name: Get packages
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: windows-build
          path: build\windows\x64\runner\Release\
